addons:
  postgresql: "9.4"

sudo: required

services:
  - postgresql

language: php

php:
  - 5.6

branches:
  only:
    - login

install:
  - composer self-update

before_script:
  - travis_retry composer self-update
  - composer install --prefer-source --dev
  - ls -l .
  - psql -c 'create database api_testing;' -U postgres
  - vendor/bin/phinx --configuration=phinx.yml migrate --environment=testing
  - php -S localhost:8000 -t web &

script: vendor/bin/behat
