language: php

php:
  - 5.4

branches:
  only:
    - login

before_script:
  - wget http://getcomposer.org/composer.phar
  - composer install --prefer-source --dev
  - psql -c 'create database api_testing;' -U postgres

script: bin/behat
