addons:
  postgresql: "9.4"

sudo: required

services:
  - postgresql

language: php

php:
  - 5.6

branches:
  only:
    - login

before_install:
  - mkdir v2
  - find . -mindepth 1 -maxdepth 1 -not -name v2 -exec mv -t v2 -- {} +
  - cd v2

install:
  - composer self-update

before_script:
  - travis_retry composer self-update
  - composer install --prefer-source --dev
  - ls -l . 
  - psql -c 'create database api_testing;' -U postgres
  - vendor/bin/phinx --configuration=phinx.yml migrate --environment=testing
  - php -S localhost:8000 -t web &

script: vendor/bin/behat
